### ISSUE TITLE
v1 roadmap

### ISSUE THREAD

**Issue by nrvnrvn** [amaizfinance/redis-operator#12]
This is an umbrella issue to hold a checklist of tasks for a `v1` release.

- [ ] refactor pkg/redis. It works fine and it was written with Redis Sentinel in mind but it is worth reviewing the implementation in order to make it less coupled internally and more testable and transparent.
- [ ] loose control over created resources, especially StatefulSet. Current approach cherry picks bits from the StatefulSet spec and it makes sense to turn Redis CRD into a thin StatefulSet wrapper to give end users more control over the generated StatefulSet hence Pods and containers (#9 is an example feature request and it is clear that it is not the last. Other kubernetes operators dealing with the same problem end up with a messed API. Feel free to look at the most popular operators, their type definitions and requests to add missing container and Pod Spec fields and you will understand what I mean).
- [ ] remove redis exporter container. There are different scenarios of gathering metrics, and side-container pattern is just one of them. Provide a short instruction on how to connect an exporter.
- [ ] research switching to kubebuilder v2. operator-sdk is built on top of kubebuilder but skews drastically in terms of features adding very little in exchange (see operator-framework/operator-sdk/issues/1758)
- [ ] allow concurrent reconciliation (see #13)

This list is subject to be extended. Discussion is open. Any feedback is welcome!

**Comment by shamil** [comment]
Nice work @nrvnrvn. Looking forward for this roadmap!

**Comment by zedtux** [comment]
Fully automatise updating the password? 😇

**Comment by nrvnrvn** [comment]
superseded by https://github.com/nrvnrvn/redis-operator/issues/1
